# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Translate-Google
version:      0.06
version_from: lib/Lingua/Translate/Google.pm
installdirs:  site
requires:
    Readonly                       1.03
    HTML::TokeParser:              2.19
    I18N::LangTags:                0.27
    LWP::UserAgent:                1.73
    Unicode::MapUTF8:              1.09
    HTTP::Request::Common          5.817

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
